<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Consumption\BlacklistService'                        => __DIR__ . '/src/Consumption/BlacklistService.php',
  'Consumption\Factory\Service\BlacklistServiceFactory' => __DIR__ . '/src/Consumption/Factory/Service/BlacklistServiceFactory.php',
);
